component: scf
name: ap-beijing_default_mzy
org: '1257933096'
app: mzy
stage: dev
inputs:
  name: mzy
  src: ./src
  runtime: Nodejs12.16
  region: ap-beijing
  description: SCF created by Tencent Serverless Toolkit for VS Code
  handler: index.main_handler
  memorySize: 128
  timeout: 3
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /
              method: GET

# For more information: https://github.com/serverless-components/tencent-scf/blob/v2/doc/configure.md